# Generated by Django 5.2.18 on 2026-10-06 15:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(max_length=20)),
                ('capacite_kg', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'La capacité doit être supérieure à 0'), django.core.validators.MaxValueValidator(1000, 'La capacité ne peut pas dépasser 1000')])),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to='entrepriseApp.entreprise')),
            ],
        ),
    ]
